image:
  repository: "ghcr.io/m1aso/analytics"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 8000

imagePullSecrets:
  - name: ghcr-creds

ingress:
  enabled: false  # exposed only via api-gateway
