extends: ["spectral:oas"]   # built-in OpenAPI rules
formats: ["oas3", "oas3_1"] # lint OAS 3.0 and 3.1
rules:
  # keep schema validity as blocking
  oas3-schema: error
  # make style-ish rules non-blocking for now
  info-contact: warn
  license-url: warn
  operation-operationId-unique: warn

