image:
  tag: "STAGING_SHA"

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  # Database Configuration
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres123@postgresql.postgresql.svc.cluster.local:5432/aiproject"
  
  # Redis Configuration (for rate limiting and sessions)
  - name: REDIS_HOST
    value: "redis-master.redis.svc.cluster.local"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    value: ""  # No password in staging
  
  # JWT Security Configuration
  - name: JWT_SECRET_KEY
    value: "staging-jwt-secret-change-in-production-use-stronger-key"
  - name: JWT_ALGORITHM
    value: "HS256"
  - name: ACCESS_TOKEN_TTL
    value: "3600"
  - name: REFRESH_TOKEN_TTL
    value: "2592000"
  
  # Rate Limiting Configuration
  - name: MAX_LOGIN_ATTEMPTS
    value: "5"
  - name: RATE_LIMIT_WINDOW
    value: "3600"
  
  # Session Management
  - name: SESSION_TTL
    value: "2592000"
  
  # Security Settings
  - name: BCRYPT_ROUNDS
    value: "12"
  
  # CORS Configuration
  - name: ALLOWED_ORIGINS
    value: "http://localhost:3000,http://localhost:8080,https://staging.yourdomain.com"
  
  # Application Settings
  - name: PORT
    value: "8000"
  - name: DEBUG
    value: "false"
  - name: LOG_LEVEL
    value: "INFO"
  - name: SQL_DEBUG
    value: "false"
  
  # Database Pool Settings
  - name: DB_POOL_SIZE
    value: "15"
  - name: DB_MAX_OVERFLOW
    value: "30"