image:
  tag: "DEV_SHA"  # overridden by CI via --set image.tag=${GITHUB_SHA}

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

env:
  # Database Configuration
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres123@postgresql.postgresql.svc.cluster.local:5432/aiproject"
  
  # Redis Configuration (for rate limiting and sessions)
  - name: REDIS_HOST
    value: "redis-master.redis.svc.cluster.local"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    value: ""  # No password in dev
  
  # RabbitMQ Configuration (for event publishing)
  - name: RABBITMQ_URL
    value: "amqp://admin:admin123@rabbitmq.rabbitmq.svc.cluster.local:5672"
  
  # JWT Security Configuration
  - name: JWT_SECRET_KEY
    value: "dev-jwt-secret-not-for-production-change-in-prod"
  - name: JWT_ALGORITHM
    value: "HS256"
  - name: ACCESS_TOKEN_TTL
    value: "3600"
  - name: REFRESH_TOKEN_TTL
    value: "2592000"
  
  # Rate Limiting Configuration
  - name: MAX_LOGIN_ATTEMPTS
    value: "5"
  - name: RATE_LIMIT_WINDOW
    value: "3600"
  
  # Session Management
  - name: SESSION_TTL
    value: "2592000"
  
  # Security Settings
  - name: BCRYPT_ROUNDS
    value: "12"
  
  # CORS Configuration
  - name: ALLOWED_ORIGINS
    value: "http://localhost:3000,http://localhost:8080,https://dev.yourdomain.com"
  
  # Application Settings
  - name: PORT
    value: "8000"
  - name: DEBUG
    value: "true"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: SQL_DEBUG
    value: "false"
  
  # Database Pool Settings
  - name: DB_POOL_SIZE
    value: "10"
  - name: DB_MAX_OVERFLOW
    value: "20"
  
  # SMTP Email Configuration (for development)
  - name: SMTP_HOST
    value: "localhost"  # Will fail gracefully in dev
  - name: SMTP_PORT
    value: "1025"
  - name: SMTP_USERNAME
    value: ""
  - name: SMTP_PASSWORD
    value: ""
  - name: SMTP_USE_TLS
    value: "false"
  - name: FROM_EMAIL
    value: "noreply@aiproject-dev.com"
  - name: FRONTEND_URL
    value: "http://docs.45.146.164.70.nip.io"