image:
  repository: ghcr-creds
  tag: latest
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: nginx
  host: 45.146.164.70.nip.io
  path: /api/auth
imagePullSecrets:
  - name: ghcr-creds
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
