replicaCount: 1

image:
  repository: "ghcr.io/M1aso/{{ .Chart.Name }}"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []  # e.g. [{ name: ghcr }]

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env: []  # e.g. [{ name: SOME_VAR, value: "value" }]

ingress:
  enabled: false
  className: nginx
  host: ""
  path: "/api/{{ .Chart.Name }}"
  annotations: {}
