image:
  repository: ghcr.io/OWNER/auth
  tag: latest
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: nginx
  host: example.local
  path: /api/auth
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
