image:
  repository: "ghcr.io/m1aso/auth"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 8000

imagePullSecrets:
  - name: ghcr-creds

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
