image:
  tag: "STAGING_SHA"

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres123@postgresql.postgresql.svc.cluster.local:5432/aiproject"
  - name: REDIS_URL
    value: "redis://redis-master.redis.svc.cluster.local:6379"
  - name: JWT_SECRET
    value: "staging-jwt-secret-change-in-production"
  - name: LOG_LEVEL
    value: "INFO"