apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "svc.fullname" . }}
  labels: { app: {{ include "svc.fullname" . }} }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ include "svc.fullname" . }} }
  template:
    metadata:
      labels: { app: {{ include "svc.fullname" . }} }
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "svc.fullname" . }}
          image: "{{ tpl .Values.image.repository . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
{{- toYaml .Values.env | nindent 16 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
