apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_http
          address:
            socket_address: { address: 0.0.0.0, port_value: {{ .Values.service.port }} }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    codec_type: AUTO
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: default
                          domains: [ {{- if .Values.ingress.host }}"{{ .Values.ingress.host }}", {{- end }}"*" ]
                          routes:
{{- range $name, $cfg := .Values.routes }}
                            - match: { prefix: "/api/{{ $name }}" }
                              route:
                                cluster: "{{ $name }}_cluster"
                                prefix_rewrite: "/"
{{- end }}
                    http_filters:
{{- if .Values.jwtAuthn.enabled }}
                      - name: envoy.filters.http.jwt_authn
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                          providers:
                            default:
                              issuer: "{{ .Values.jwtAuthn.issuer }}"
                              remote_jwks:
                                http_uri:
                                  uri: "{{ .Values.jwtAuthn.jwksUri }}"
                                  cluster: jwks_cluster
                                  timeout: 5s
                              forward_payload_header: "x-jwt-payload"
                          rules:
                            - match: { prefix: "/" }
                              requires: { provider_name: "default" }
{{- end }}
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
{{- if .Values.jwtAuthn.enabled }}
        - name: jwks_cluster
          type: STRICT_DNS
          connect_timeout: 2s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: jwks_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "{{ .Values.jwtAuthn.jwksHost }}"
                          port_value: {{ .Values.jwtAuthn.jwksPort }}
{{- end }}
{{- range $name, $cfg := .Values.routes }}
        - name: "{{ $name }}_cluster"
          type: STRICT_DNS
          connect_timeout: 2s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: "{{ $name }}_cluster"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "{{ $cfg.serviceName }}.{{ $.Release.Namespace }}.svc.cluster.local"
                          port_value: {{ $cfg.servicePort }}
{{- end }}
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }
