apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels: { app: api-gateway }
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c", "/etc/envoy/envoy.yaml", "--disable-hot-restart"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: admin
              containerPort: 9901
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          readinessProbe:
            httpGet:
              path: /ready
              port: admin
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: envoy-config
          configMap:
            name: api-gateway-config
            items:
              - key: envoy.yaml
                path: envoy.yaml
