openapi: 3.1.0
info:
  title: Notifications API
  version: 0.2.0
servers:
  - url: http://api.45.146.164.70.nip.io
    description: Development server
paths:
  /api/notifications/healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK

  /api/notifications/send:
    post:
      summary: Queue a notification for delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [channel, recipient, template]
              properties:
                channel:
                  type: string
                  enum: [email, sms, push]
                recipient:
                  type: string
                template:
                  type: string
                data:
                  type: object
                idempotency_key:
                  type: string
      responses:
        '202': { description: Queued }

  /api/notifications/preview:
    post:
      summary: Render a notification without sending
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [channel, template]
              properties:
                channel:
                  type: string
                  enum: [email, sms, push]
                template:
                  type: string
                data:
                  type: object
      responses:
        '200': { description: Rendered }

  /api/notifications/subscriptions:
    get:
      summary: Get current user notification subscriptions
      responses:
        '200': { description: OK }
    put:
      summary: Update current user notification subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '200': { description: Updated }
