global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application services (when running locally)
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'profile-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'content-service'
    static_configs:
      - targets: ['host.docker.internal:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'notifications-service'
    static_configs:
      - targets: ['host.docker.internal:8004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'chat-service'
    static_configs:
      - targets: ['host.docker.internal:8005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:8006']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Infrastructure services
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 60s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 60s
