-- +goose Up
ALTER TABLE courses ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sections ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE materials ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE media_assets ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tags ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tags ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE tags DROP COLUMN updated_at;
ALTER TABLE tags DROP COLUMN created_at;
ALTER TABLE media_assets DROP COLUMN updated_at;
ALTER TABLE materials DROP COLUMN updated_at;
ALTER TABLE sections DROP COLUMN updated_at;
ALTER TABLE courses DROP COLUMN updated_at;
