{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "svc.fullname" . }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ tpl .Values.ingress.path . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "svc.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
