image:
  repository: "ghcr.io/m1aso/chat"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 8000

env:
  - name: REDIS_URL
    value: redis://redis:6379

imagePullSecrets:
  - name: ghcr-creds

ingress:
  enabled: false  # exposed only via api-gateway
