image:
  repository: "ghcr.io/m1aso/chat"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8000

env:
  - name: REDIS_URL
    value: "redis://redis:6379"  # You'll need to deploy Redis
  - name: DATABASE_URL
    value: "sqlite:///app/data/chat.db"
  - name: ENVIRONMENT
    value: "production"

imagePullSecrets:
  - name: ghcr-creds

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70