image:
  tag: "DEV_SHA"  # overridden by CI via --set image.tag=${GITHUB_SHA}

service:
  port: 8000

env:
  - name: REDIS_URL
    value: redis://redis:6379

imagePullSecrets:
  - name: ghcr

ingress:
  enabled: false  # exposed only via api-gateway
