image:
  tag: "DEV_SHA"  # overridden by CI via --set image.tag=${GITHUB_SHA}

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

env:
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres123@postgresql.postgresql.svc.cluster.local:5432/aiproject"
  - name: REDIS_URL
    value: "redis://redis-master.redis.svc.cluster.local:6379"
  - name: RABBITMQ_URL
    value: "amqp://admin:admin123@rabbitmq.rabbitmq.svc.cluster.local:5672"
  - name: MINIO_ENDPOINT
    value: "minio.minio.svc.cluster.local:9000"
  - name: MINIO_ACCESS_KEY
    value: "admin"
  - name: MINIO_SECRET_KEY
    value: "admin123456"
  - name: MINIO_SECURE
    value: "false"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: CONTENT_API_URL
    value: "http://api.45.146.164.70.nip.io"
  - name: CONTENT_WORKER_API_KEY
    value: "dev-content-worker-api-key-change-in-prod"
