image:
  repository: "ghcr.io/m1aso/content"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8000

imagePullSecrets:
  - name: ghcr-creds

env:
  - name: DATABASE_URL
    value: "sqlite:///app/data/content.db"
  - name: ENVIRONMENT
    value: "production"

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70