replicaCount: 1

image:
  repository: "ghcr.io/m1aso/{{ .Chart.Name }}"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []  # e.g. [{ name: ghcr }]

service:
  port: 8000

resources: {}

env: []  # e.g. [{ name: SOME_VAR, value: "value" }]

ingress:
  enabled: false
  className: nginx
  host: ""
  path: "/api/{{ .Chart.Name }}"
  annotations: {}
