{{- if (dig "hpa" "enabled" false .Values) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}
spec:
  minReplicas: {{ dig "hpa" "minReplicas" 1 .Values }}
  maxReplicas: {{ dig "hpa" "maxReplicas" 3 .Values }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ dig "hpa" "targetCPUUtilizationPercentage" 70 .Values }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
{{- end }}
