replicaCount: 1

image:
  repository: "ghcr.io/M1aso/profile"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []  # e.g. [{ name: ghcr }]

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  - name: MINIO_ENDPOINT
    value: "minio:9000"
  - name: MINIO_BUCKET
    value: "avatars"

ingress:
  enabled: false
  className: nginx
  host: ""
  path: "/api/{{ .Chart.Name }}"
  annotations: {}
