image:
  tag: "DEV_SHA"  # overridden by CI via --set image.tag=${GITHUB_SHA}

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

env:
  DATABASE_URL: "postgresql://postgres:postgres123@postgresql.postgresql.svc.cluster.local:5432/aiproject"
  MINIO_ENDPOINT: "minio.minio.svc.cluster.local:9000"
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "admin123456"
  MINIO_SECURE: "false"
  MINIO_BUCKET: "avatars"
  LOG_LEVEL: "DEBUG"
  JWT_SECRET_KEY: "dev-jwt-secret-not-for-production-change-in-prod"
  JWT_ALGORITHM: "HS256"

migrations:
  enabled: true

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
