image:
  tag: "DEV_SHA"  # overridden by CI via --set image.tag=${GITHUB_SHA}

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

env:
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres123@postgresql.postgresql.svc.cluster.local:5432/aiproject"
  - name: MINIO_ENDPOINT
    value: "minio.minio.svc.cluster.local:9000"
  - name: MINIO_ACCESS_KEY
    value: "admin"
  - name: MINIO_SECRET_KEY
    value: "admin123456"
  - name: MINIO_SECURE
    value: "false"
  - name: MINIO_BUCKET
    value: "avatars"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: JWT_SECRET_KEY
    value: "dev-jwt-secret-not-for-production-change-in-prod"
  - name: JWT_ALGORITHM
    value: "HS256"

# Migration Configuration
migrations:
  enabled: true
  timeout: 120  # 2 minutes for dev
  retries: 2    # Reduced retries for dev
  waitForDatabase: true

ingress:
  enabled: false  # exposed only via api-gateway

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
