replicaCount: 1

image:
  repository: "ghcr.io/m1aso/{{ .Chart.Name }}"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []  # e.g. [{ name: ghcr }]

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env: []  # e.g. [{ name: SOME_VAR, value: "value" }]

# Migration Configuration
migrations:
  enabled: true
  timeout: 300  # 5 minutes
  retries: 3
  waitForDatabase: true

ingress:
  enabled: false
  className: nginx
  host: ""
  path: "/api/{{ .Chart.Name }}"
  annotations: {}
