image:
  tag: "DEV_SHA"  # overridden by CI via --set image.tag=${GITHUB_SHA}

service:
  port: 8000

imagePullSecrets:
  - name: ghcr

env:
  - name: MINIO_ENDPOINT
    value: "minio:9000"
  - name: MINIO_BUCKET
    value: "avatars"

ingress:
  enabled: false  # exposed only via api-gateway
