name: notifications docker

on:
  push:
    branches: [main]
    paths:
      - 'services/notifications/**'
      - '.github/workflows/docker-notifications.yml'
  pull_request:
    paths:
      - 'services/notifications/**'
      - '.github/workflows/docker-notifications.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./services/notifications
          file: ./services/notifications/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/notifications:latest
